### ISSUE TITLE
The wheels of a car don't move

### ISSUE THREAD

**Issue by ddwy** [srmainwaring/curio#9] opened 2020-11-13 11:53 UTC
Hello, can you provide the hardware wiring diagram and the curio firmware？

Here is my hardware wiring diagram. If there is any error, please point it out for me.

Thank you 

![image](https://user-images.githubusercontent.com/43903311/99069705-d7057980-25e9-11eb-890a-9ec68cb5638f.png)
![image](https://user-images.githubusercontent.com/43903311/99069710-db319700-25e9-11eb-9f33-e715911fde8a.png)
![image](https://user-images.githubusercontent.com/43903311/99069715-de2c8780-25e9-11eb-94ff-ec19f9b29f13.png)

**Comment by srmainwaring** [comment] 2020-11-14 00:20
@ddwy The serial connection between the BusLinker servo board and the Arduino should not use TX0 / RX0 (Serial) as it this UART is also used to communicate with the computer by USB (see for example: [Arduino Serial Reference](https://www.arduino.cc/en/pmwiki.php?n=Reference/serial)). This would explain why you are seeing the ROS serial connection sync issues here [1 #4](https://github.com/srmainwaring/curio_firmware/issues/4).

In `curio_firmware.ino` Serial1 is used to connect to the servo bus. This uses pins 18 and 19 on the Arduino Mega.

https://github.com/srmainwaring/curio_firmware/blob/1fbf725c350dac708893b4af6523db931e931abb/firmware/curio_firmware/curio_firmware.ino#L172

I don't have a wiring diagram but have attached photos of my set up. The Arduino is hiding under the breadboard (which holds an IMU and a Teensy4 which is used to relay the IMU and RC data onto ROS serial). I am only using the Arduino to relay the serial commands between the BusLinker board and the RPi4.

The Buslinker is in the middle and the power regulator providing the 5V supply is above it.  

![IMG_7263](https://user-images.githubusercontent.com/24916364/99132090-f06bed00-260c-11eb-9c20-af2e545c63ba.jpg)

The second photo shows the connection from BusLinker RX (yellow) to pin 18 (Arduino Mega TX1) and BusLinker TX (green) to pin 18 (Arduino Mega RX1). I use the 5V supply near the UART pins, but that is neither here nor there.
   
![IMG_7260](https://user-images.githubusercontent.com/24916364/99132099-f5c93780-260c-11eb-930a-0082818df5b7.jpg)

I also notice you have a micro USB on the BusLinker board. I have used this for a [optional failsafe](https://github.com/srmainwaring/curio#test-the-base-failsafe-node-optional), but to start with I'd disconnect that to avoid confusion.

**Comment by ncnynl** [comment] 2020-11-20 02:37
Hello srmainwaring

I debugged the curio code and found that as long as ros is introduced, the servo cannot be controlled normally. The problem is that serial1 cannot output normally. LobotSerialServoAngleAdjust function can be executed normally, SerialX.write cannot take effect. The default definition servo uses serial1 as the serial port for controlling the servo, and serial as the serial port for ros interaction. I use the serial cable to monitor serial1 alone, but there is no output.

I suspect it is, but after the introduction of ros, serial will cause serial1, 2, and 3 to fail. I have tested 1, 2, and 3 serial ports, but there is no output. If ros is not introduced, several serial ports are working normally.

**Comment by srmainwaring** [comment] 2020-11-20 13:42
@ncnynl I have not seen the issue you describe when using ROS serial to communicate with an Arduino that is connected to the BusLinker on Serial1. I have seen ROS lose sync with the Arduino when data rates get too high or missed packets between the BusLinker and Arduino. The serial baud rate for `ros_serial` and servo loop update frequencies have been tuned to try and minimise this.

To help me replicate the problem you are seeing could you describe the hardware and software setup you are using for testing . The following would be helpful:

**Hardware**

- a description of the wiring connections between PC and Arduino and Arduino and BusLinker that you are using to conduct tests

**Software**

- PC operating system
- ROS version
- `ros_serial` version
- tools used for monitoring outputs from RX1, RX2, etc,   (logical analyser or UART to USB)  
 
And anything else you think relevant.

**Comment by ncnynl** [comment] 2020-11-24 01:35
@srmainwaring  

hi srmainwaring

I have tested the code and it runs normally. 

At the beginning, I modified the servo ID under windows and flashed the firmware through arduino, but it didn't work normally. Later, I moved this modified code to Linux, and then flashed the firmware, but it didn't work properly. 

Later, I tested a minimal version of ros and it worked normally. 

Then I downloaded the code directly from github to linux to flash the firmware. is normal. 

The code is ok. 

It may be a problem with my modified version under windows that caused it to not work properly.

**Comment by srmainwaring** [comment] 2020-11-24 09:50
@ncnynl I have not tested the ROS code under Windows, only linux and macOS. It may be that when you copied from Windows to linux the line endings were changed which gave rise to the issues you saw?

In any case it is good to hear that you have the software working now and I'll close the issue.

**Closed as completed by srmainwaring** 2020-11-24 09:50 UTC
